# Copyright IBM Corp. 2017 All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  couchdb0:
    image: hyperledger/fabric-couchdb${COUCHDB0_VERSION_EXTENSION}
    ports:
      - '5984'
    volumes:
      - ${COUCHDB0_HOST_DATA_DIR}:/opt/couchdb/data

  peer0:
    environment:
       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    depends_on:
       - couchdb0

  couchdb1:
    image: hyperledger/fabric-couchdb${COUCHDB1_VERSION_EXTENSION}
    ports:
      - '5984'
    volumes:
      - ${COUCHDB1_HOST_DATA_DIR}:/opt/couchdb/data

  peer1:
    environment:
       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    depends_on:
       - couchdb1

  couchdb2:
    image: hyperledger/fabric-couchdb${COUCHDB2_VERSION_EXTENSION}
    ports:
      - '5984'
    volumes:
      - ${COUCHDB2_HOST_DATA_DIR}:/opt/couchdb/data

  peer2:
    environment:
       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    depends_on:
       - couchdb2

  couchdb3:
    image: hyperledger/fabric-couchdb${COUCHDB3_VERSION_EXTENSION}
    ports:
      - '5984'
    volumes:
      - ${COUCHDB3_HOST_DATA_DIR}:/opt/couchdb/data

  peer3:
    environment:
       - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    depends_on:
       - couchdb3
